# -*- coding: utf-8 -*-
"""Facil de 6. Clasificación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QLW7Tq10qmaQyqXv3TOI6-q977_Ornj

**Contexto**

En 2020, en todo el mundo se diagnosticó cáncer de mama a 2,3 millones de mujeres, y 685 000 fallecieron por esa enfermedad. A fines del mismo año, 7,8 millones de mujeres a las que en los anteriores cinco años se les había diagnosticado cáncer de mama seguían con vida, lo que hace que este cáncer sea el de mayor prevalencia en el mundo.

Se estima que, a nivel mundial, los años de vida perdidos ajustados en función de la discapacidad (AVAD) en mujeres con cáncer de mama superan a los debidos a cualquier otro tipo de cáncer.

El cáncer de mama afecta a las mujeres de cualquier edad después de la pubertad en todos los países del mundo, pero las tasas aumentan en su vida adulta.

Entre las décadas de 1930  y 1970, la mortalidad por cáncer de mama mostró pocos cambios. Las mejoras en la supervivencia empezaron en los años 1980 en países que contaban con programas de detección precoz combinados con diferentes tipos de terapias para contener la enfermedad invasiva.

**Descripción**

El cáncer de mama se origina en las células del revestimiento (epitelio) de los conductos (85%) o lóbulos (15%) del tejido glandular de los senos. Al comienzo, el tumor canceroso está confinado en el conducto o lóbulo (in situ), donde generalmente no causa síntomas y tiene un mínimo potencial de diseminación (metástasis).

Con el paso del tiempo, este cáncer in situ (estadio 0) puede progresar e invadir el tejido mamario circundante (cáncer de mama invasivo), y a continuación propagarse a los ganglios linfáticos cercanos (metástasis regional) u a otros órganos del organismo (metástasis distante). Cuando una mujer muere de cáncer de mama, es como consecuencia de la metástasis generalizada.  

El tratamiento del cáncer de mama puede ser muy eficaz, en particular cuando la enfermedad se detecta temprano. A menudo el tratamiento consiste en una combinación de extirpación quirúrgica, radioterapia y medicación (terapia hormonal, quimioterapia y/o terapia biológica dirigida) para tratar el cáncer microscópico que se ha propagado del tumor mamario a través de la sangre. Por consiguiente, ese tratamiento, que puede impedir la progresión y diseminación del cáncer, salva vidas.

**Estado del arte**

El cáncer de mama es el tipo de cáncer más común, con más de 2,2 millones de casos en 2020.

Cerca de una de cada 12 mujeres enfermarán de cáncer de mama a lo largo de su vida. El cáncer de mama es la principal causa de mortalidad en las mujeres. En 2020, alrededor de 685 000 mujeres fallecieron como consecuencia de esa enfermedad.

La mayoría de los casos de cáncer de mama y de las muertes por esa enfermedad se registran en países de ingresos bajos y medianos.

Las disparidades del cáncer de mama entre los países de ingresos elevados y los de ingresos bajos y medianos son considerables. La supervivencia al cáncer de mama a cinco años excede del 90% en los primeros países, mientras que en la India y Sudáfrica es del 66% y el 40%, respectivamente.

El mayor porcentaje normalizado por edades[1] de defunciones por cáncer de mama corresponde a África y Polinesia. En el África subsahariana, la mitad de las muertes por cáncer de mama se produce en mujeres menores de 50 años de edad.

Desde 1980 se han realizado importantes avances en el tratamiento del cáncer de mama; entre el decenio de 1980 y 2020, en los países de ingresos elevados la mortalidad por cáncer de mama normalizada por edades se redujo en un 40%. En los países de ingresos bajos y medianos esas mejoras todavía no se han logrado.

La mejora de los resultados es fruto de la combinación de la detección precoz y las terapias eficaces, basadas en cirugía, radioterapia y farmacoterapia.

**Problema a solucionar**

Se definió anteriormente el contexto. Cómo podemos ayudar mediante los datos.

Aplica los distintos algoritmos vistos en la teoría de este módulo hasta obtener un clasificador con score, accuracy, precision, recall y f1-score igual o superior a 0.95 .

No olvides probar a optimizar los diferentes hiperparámetros de cada algoritmo.

**Obtención de datos**

Todo problema de data science y machine learning no es nada sin sus datos. El primer problema es cómo obtenerlos.

Por suerte, en esta ocasión, ya se han recopilado por varios médicos para que podamos trabajar en ello.


[Enlace a carpeta github con dataset y nombres de las columnas](https://github.com/nodd3r/recursos/tree/main/datasets/cancer)
"""

#Crea el DataFrame correspondiente en la variable datos (no olvides comprobar el encabezado y añadir el nombre correspondiente a cada columna)
import pandas as pd
datos=pd.read_csv('https://raw.githubusercontent.com/nodd3r/recursos/main/datasets/cancer/breast-cancer-wisconsin.data.txt')
datos.head()

#@title Comprueba que la creacción del DataFrame sea correcta
def check():
  if list(datos.columns.values)==['ID','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class']:
    return 'Correcto'
  else:
    return 'Incorrecto. Comprueba la creacción del Dataframe'

check()

"""**Entiende los datos**

Una vez creado el DataFrame debes realizar, como siempre, un análisis exploratorio de los datos para ver:
* Tipos de datos
* columnas
* qué significa
* qué valores pueden tener
* si existen valores nulos
* la distribuccion que siguen los datos de cada columna
* etc.

Ayudate de gráficos para un entendimiento más visual.
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#Realiza el EDA que creas conveniente
datos.info()

datos['Bare Nuclei']= datos['Bare Nuclei'].replace('?', np.nan)
datos = datos.dropna()

datos['Bare Nuclei']= datos['Bare Nuclei'].astype('int64')

datos.info()

datos['Class']=datos['Class'].replace(2,0)
datos['Class']=datos['Class'].replace(4,1)

datos['Class'].value_counts()



"""#Entrena diferentes modelos variando el algoritmo y los hiperparámetros de los mismos.

Recuerda que debes obtener un clasificador que iguale o supere un score, precision, recall y f1-score de 0.95.

Al realizar la separaccion en subconjuntos de entrenamiento y comprobación es recomendable mantener el % de muestras de cada clase (mediante el parámetro stratify=y de la función train_test_split).

Aunque no es necesario para superar el ejercicio, una forma de mejorar los resultados es balancear los datos ([Documentación Resample](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html)), este paso debe realizarse antes de entrenar al algoritmo.

Una vez hayas conseguido un modelo que iguale o supere la puntuación requerida almacénalo en la variable modelo_definitivo.

ej:

    clf=GaussianNB()

    clf.fit(X,Y)

    clf.slcore(X_test,Y_test)

    clf2=LogisticRegresion(solver='saga')

    clf2.fit(X,Y)

    clf2.score(X_test,Y_test)

Una vez que algúno, supongamos en este caso que es el Naive-Bayes,tengan un score y el resto de métricas igual o por encima de 95%

    modelo_definitivo= clf
"""

#Prueba diferentes algoritmos con diferentes parámetros hasta cumplir los requisitos.

from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = datos.loc[:, datos.columns != 'Class']
y = datos['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

model_lr=LogisticRegression()
model_lr.fit(X_train, y_train)
model_lr.score(X_test, y_test)

model_lr=DecisionTreeClassifier()
model_lr.fit(X_train, y_train)
model_lr.score(X_test, y_test)

#Iguala la variable modelo_definitivo al clasificador que cumpla las exigencias de superar el 0.95 en la puntuacion y las metricas.

modelo_definitivo=model_lr

#@title Comprueba que tu algoritmo cumpple los requisitos
def check_2():

  X_token=pd.read_csv('https://raw.githubusercontent.com/nodd3r/recursos/main/datasets/cancer/Token/X_token.csv', header=0)
  Y_token=pd.read_csv('https://raw.githubusercontent.com/nodd3r/recursos/main/datasets/cancer/Token/Y_token.csv', header=0)
  puntuacion=model_lr.score(X_token,Y_token)
  if puntuacion>=0.95:

    Y_token_pred=model_lr.predict(X_token)
    from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score
    metrics_label=['accuracy', 'precision','recall','f1-score']
    metrics=[accuracy_score(Y_token,Y_token_pred), precision_score(Y_token,Y_token_pred), recall_score(Y_token,Y_token_pred), f1_score(Y_token,Y_token_pred)]
    if min(metrics)>=0.95:
      return 'Correcto'
    else:
      return f'La métrica {metrics_label[metrics.argmin()]} tiene un valor de {min(metrics)}, no cumple el objetivo de igualar o superar 0.95'
  else:
       return f'La puntuacion del algoritmo es: {puntuacion}, no cumple el objetivo de igualar o superar 0.95'

check_2()

#@title Consigue el Token para validar el ejercicio en Nodd3r
import hashlib

correct = str(check()) + str(check_2())
pwd = hashlib.sha256(str(correct).encode())
print('El token para corregir en Nodd3r es:\n',pwd.hexdigest())